"""Structured server-side timing instrumentation for the learner path.

`phase()` wraps a logical step (settings load, controller resolution, a
DB write, ...) and logs one structured line with the step's wall-clock
elapsed time plus the number and total time of any SQL statements executed
anywhere underneath it -- attribution works across module boundaries (e.g.
app/flow.py calling into recommendation/sqlite_repository.py) because the
SQLAlchemy `before/after_cursor_execute` events below are global (installed
once, on the `Engine` class) and simply add to whichever `phase()` is
innermost-active on the current thread, via a contextvar. Phases can nest:
a query executed inside a nested phase is counted on that phase and also
rolled up into every ancestor phase, so an outer "total_submit_rerun" phase
reports the sum of everything that happened inside it.

correlation_id is also contextvar-propagated: the outermost phase() of one
Streamlit rerun generates it once; every nested phase() further down the
call stack -- including inside app/controller.py, bkt/service.py, and
recommendation/service.py -- picks it up automatically with no signature
changes needed on any of those methods, so this instrumentation stays
additive-only over the existing learner-path code.

Never logs learner IDs, submitted answers, database URLs, or credentials --
only a phase name, the per-run correlation_id, course_id, elapsed_ms, and
aggregate DB query count/time.
"""

import logging
import time
import uuid
from contextlib import contextmanager
from contextvars import ContextVar

from sqlalchemy import event
from sqlalchemy.engine import Engine

LOGGER = logging.getLogger("app.perf")

_current_frame: ContextVar["_Frame | None"] = ContextVar("_current_frame", default=None)
_current_correlation_id: ContextVar[str | None] = ContextVar(
    "_current_correlation_id", default=None
)


class _Frame:
    __slots__ = ("parent", "query_count", "db_time_ms")

    def __init__(self, parent: "_Frame | None") -> None:
        self.parent = parent
        self.query_count = 0
        self.db_time_ms = 0.0


def new_correlation_id() -> str:
    return uuid.uuid4().hex[:12]


@event.listens_for(Engine, "before_cursor_execute")
def _before_cursor_execute(conn, cursor, statement, parameters, context, executemany):
    context._perf_start = time.perf_counter()


@event.listens_for(Engine, "after_cursor_execute")
def _after_cursor_execute(conn, cursor, statement, parameters, context, executemany):
    frame = _current_frame.get()
    if frame is None:
        return
    start = getattr(context, "_perf_start", None)
    if start is None:
        return
    frame.query_count += 1
    frame.db_time_ms += (time.perf_counter() - start) * 1000


@contextmanager
def phase(
    name: str,
    *,
    correlation_id: str | None = None,
    course_id: str | None = None,
    **extra: object,
):
    """Time one logical step. Extra keyword args (e.g. cache_hit=True) are
    appended to the log line as key=value; never pass learner-identifying
    or secret values here.

    correlation_id: pass explicitly only at a request's outermost phase
    (e.g. app/main.py's per-rerun phases) if you want a caller-chosen id;
    otherwise omit it everywhere and nested phases automatically share the
    id generated by the outermost phase of the current call stack."""
    correlation_token = None
    if correlation_id is None:
        correlation_id = _current_correlation_id.get()
        if correlation_id is None:
            correlation_id = new_correlation_id()
            correlation_token = _current_correlation_id.set(correlation_id)
    else:
        correlation_token = _current_correlation_id.set(correlation_id)

    parent = _current_frame.get()
    frame = _Frame(parent)
    token = _current_frame.set(frame)
    start = time.perf_counter()
    try:
        yield
    finally:
        elapsed_ms = (time.perf_counter() - start) * 1000
        _current_frame.reset(token)
        if frame.parent is not None:
            frame.parent.query_count += frame.query_count
            frame.parent.db_time_ms += frame.db_time_ms
        extras = "".join(f" {key}={value}" for key, value in extra.items())
        LOGGER.info(
            "phase=%s correlation_id=%s course_id=%s elapsed_ms=%.2f "
            "db_queries=%d db_time_ms=%.2f%s",
            name,
            correlation_id,
            course_id or "-",
            elapsed_ms,
            frame.query_count,
            frame.db_time_ms,
            extras,
        )
        if correlation_token is not None:
            _current_correlation_id.reset(correlation_token)
